### ISSUE TITLE
Should getting started be a title?

### ISSUE THREAD

**Issue by peterbollen** [javaslang/javaslang-docs#15]
Just above http://www.javaslang.io/javaslang-docs/#_gradle there is a getting started section that is not being formatted correctly.

> don’t hesitate to send pull requests.
> == Getting started

**Comment by danieldietrich** [comment]
Thank you, I will take a look.

**Comment by danieldietrich** [comment]
@RobWin it seems that the first line of each include (starting with the second) is not formatted. All first lines are second level headlines `== headline` I think.

Do you have seen this before with asciidoc? Is this an eof / newline problem?

**Comment by RobWin** [comment]
@danieldietrich There must be a new line in front of each Section title. Either you can do it in the index.adoc or in each included file.

**Comment by danieldietrich** [comment]
Thx, fixed! Works like a charm.
