### ISSUE TITLE
Incorrect merge

### ISSUE THREAD

**Issue by perceptron8** [javaslang/javaslang-docs#18]
There's something wrong with 67fb6983c887ed551cf3e9b903743fc12d6ba03a. Look for
`a818a75b55c800492902ae8d9946c30c88c3c62a` here and there...

Check http://www.javaslang.io/javaslang-docs/#_lazy for example.

**Comment by danieldietrich** [comment]
Wow, thanks for the hint - will fix it immediately!

**Comment by danieldietrich** [comment]
Fixed!

**Comment by perceptron8** [comment]
Thanks!
